sudo: false
language: java
addons:
  apt_packages:
   - python-pip
   - python-virtualenv
   - libevent-dev
script:
 - mvn test
# TODO: disable s3-tests due to a Travis regression
# - ./src/test/resources/run-s3-tests.sh
